name: Productive Time

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  productive:
    runs-on: ubuntu-latest

    steps:
      - name: Update Productive Box
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: fd0b19ce8a9a0f08390ab943c4803fd6
          TIMEZONE: Asia/Seoul
